### ISSUE TITLE
Resumen "Artefactos"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#11]
Resumen de una parte del tercer tema principios y valores scrum

**Comment by CarmenRu** [comment]
Acabo de subir el resumen, cuando puedas dime que te parece o si algo le falta y en caso de estar bien lo cerramos

**Comment by alc1020** [comment]
el resumen está muy bien, no te has dejado ningun punto sin resumir. se puede cerrar
xoxo
