### ISSUE TITLE
Resumen "Prácticas para flexibilizar scrum"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#13]
Resumen de una parte del tercer tema principios y valores scrum

**Comment by CarmenRu** [comment]
Por último acabo de subir el resumen que faltaba, lo mismo que en los otros dos, cuando lo puedas echar un vistazo, agradecida.

**Comment by CarmenRu** [comment]
Te lo he pasado a review que hay veces que no se ve aunque ahora veo que esta marcado en esta propia tarea

**Comment by alc1020** [comment]
Esta muy bien, yo lo hubiera hecho mas corto pero creo que está bien como está.
