### ISSUE TITLE
Diagrama conceptual "Medición y estimación ágil"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#16]
Diagrama de una parte del segundo tema ciclo scrum

**Comment by hrg1002** [comment]
voy a cambiar la etiqueta porque es de conceptos 2 :)

**Comment by hrg1002** [comment]
voy a cambiar la label porque es de conceptos 2 :)

**Comment by alc1020** [comment]
si perdona que pensaba que entraba en nuestro bloque, pero gracias por pillarlo

**Comment by alc1020** [comment]
voy a cambiar los asignados
