### ISSUE TITLE
Glosario de términos "Principios y valores scrum"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#28]
De 8 a 15 términos interesantes que se encuentran en el tercer tema

**Comment by alc1020** [comment]
Entre mañana y pasado aportaré unos términos al issue

**Comment by alc1020** [comment]
en el apartado de principios del tercer bloque hay muchos terminos con definiciones, de todas maneras deberiamos poder conseguir dos terminos por apartados

**Comment by alc1020** [comment]
Que te parece si yo me fijo en los primero tres apartados y tu en los otros, y luego nos corregimos entre nosotras?

**Comment by CarmenRu** [comment]
Vale, me parece buena idea, estos dias estare un poco ausente por la semana santa pero hare mis tareas de todas maneras te voy informando por aqui

**Comment by alc1020** [comment]
Hoy colgaré unos términos y lo moveré a revisión para que los revises. Cuando aportes las tuyas muelevos a progreso de nuevo, y despues a revisión si quieres que los mire

**Comment by alc1020** [comment]
Aquí te cuelgo algunas. Considero que hay algunas mejores que otras y quisiera saber que opinas.
**Ritmo de trabajo sostenible:** Ritmo de trabajo que se debe mantener de una manera indefinida.
**Asertividad**: Capacidad de defender tu trabajo o ajena de forma positiva.
**Autodisciplina**: Exigencia que se tiene a uno mismo de forma voluntaria.
**Transparencia**: Honestidad, no ocultar nada al equipo.
**Compromiso**: Acuerdo formal al que llegan dos o más partes tras hacer ciertas concesiones cada una de ellas.
**Adaptación**: Capacidad de adecuarse a cambios de circunstancias.
**Valor**: Cualidad(es) aporta apreciación de algún tipo por una persona, organización, sociedad, etc.

**Comment by CarmenRu** [comment]
Yo he considerado estos términos.
Product owner: Es el propietario del proyecto en realidad, el que dice que quiere y para cuando.
Variabilidad: dispersión de los valores de una variable en una distribución teórica o en una muestra
Incremento: Cuando hablamos de un incremento en este libro nos referimos a una issue realizada
Issue: Significa tarea que están dentro de los milestones
Impedimento: Obstáculo o impedimento para algo

**Comment by CarmenRu** [comment]
Igual podemos cambiar alguno de los tuyos por alguno de los mios

**Comment by CarmenRu** [comment]
Yo de los tuyos solo considero que adaptación no es del todo necesario, mira a ver si hay alguno mio que no te cuadra pero en principio de los demas que aportaste me parecen bien todos

**Comment by alc1020** [comment]
De acuerdo, ahora los reviso

**Comment by alc1020** [comment]
Impedimento no me parece totalmente adecuado. El resto estan muy bien.
