### ISSUE TITLE
Preguntas "Principios y valores scrum"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#3]
Posibles preguntas de examen apartado principios y valores scrum

**Comment by alc1020** [comment]
Hoy añadiré las preguntas

**Comment by alc1020** [comment]
He agregado las preguntas, disculpa el retraso

**Comment by CarmenRu** [comment]
Ahora mismo hago las respuestas, puedes cerrar este issue

**Comment by alc1020** [comment]
Me parecen bien las respuestas, por lo que he cerrado el issue
