### ISSUE TITLE
Resumen "Medición y estimación ágil"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#7]
Resumen de una parte del segundo tema ciclo scrum

**Comment by alc1020** [comment]
entre hoy y mañana subiré mis textos y si puedes revisarlos a ver que te parecen estaría fetén

**Comment by alc1020** [comment]
He subido ahora el resumen de medicion y estimacion agil. Miralo cuando quieras.

**Comment by CarmenRu** [comment]
Este me parece bien y tocas los puntos importantes del tema asiq yo lo daría por terminado tambien

**Comment by alc1020** [comment]
cerrado.
