### ISSUE TITLE
Resumen "Principios"

### ISSUE THREAD

**Issue by CarmenRu** [hrg1002/Tarea-1#8]
Resumen de una parte del tercer tema principios y valores scrum

**Comment by alc1020** [comment]
He subido el resumen de principios. Voy a cerrar este issue y el de medicion pero miralos y me comentas algun cambio que quieras hacer

**Comment by CarmenRu** [comment]
Lo acabo de leer y el resumen me parece adecuado, por mi los puedes cerrrar

**Comment by alc1020** [comment]
genial gracias

**Comment by alc1020** [comment]
pensaba que habia un error en mis resumenes. los cerrare todos de inmediato
